### List all Orders - deep read
GET http://localhost:4004/admin/Orders?
&$expand=Items

### Without Items
GET http://localhost:4004/admin/Orders

### Submit Orders - deep insert. Doesnt work with admin serv impl
POST http://localhost:4004/browse/Orders
Content-Type: application/json

{ "OrderNo":"1234", "Items":[
    { "book_ID":201, "amount":5 },
    { "book_ID":207, "amount":3 }
]}

### Try to get the Orders. Fail bc Orders is @insertonly
GET http://localhost:65315/browse/Orders

### List Books with their current stocks
GET http://localhost:4004/admin/Books?$select=ID,stock
